

#-------------------------------
# About Section


blurb: >
  **Julia specializes** in **user-centered** web development and systems analysis.
  Most of the things she builds are **for library users and staff**.</p><p>
  She is the **Web Services Librarian**
  at [Towson University Libraries](http://libraries.towson.edu).


skills:
- {name: Communication, value: '9'}
- {name: Project Management, value: '6'}
- {name: Learning, value: '9'}
- {name: Teaching, value: '6'}
- {name: Systems Evaluation, value: '8'}
- {name: Programming, value: '6'}
- {name: Visual Design, value: '7'}
- {name: UX Research, value: '5'}